[global]
    workgroup = NOVACODE
    realm = NOVACODE.LOCAL
    netbios name = SRVLIN40
    server role = active directory domain controller
    dns forwarder = 8.8.8.8
    idmap_ldb:use rfc2307 = yes
    log file = /var/log/samba/%m.log
    log level = 1

[sysvol]
    path = /var/lib/samba/sysvol
    read only = No

[netlogon]
    path = /var/lib/samba/sysvol/novacode.local/scripts
    read only = No

# Recurs anonim (P4.6 Ex3)
[software]
    comment = Software disponible anonimament
    path = /var/software
    read only = Yes
    guest ok = Yes
    browseable = Yes

# cHisenda: gDireccio escriptura
# Escriptura: uDirectora SI | Denegat: uDesenvolupadora NO
[cHisenda]
    comment = Hisenda i comptabilitat - Direccio
    path = /var/NovaCode/cHisenda
    valid users = @gDireccio
    write list = @gDireccio
    read only = No
    browseable = Yes
    create mask = 0770
    directory mask = 0770

# cComptes: gOficines escriptura, gDireccio lectura
[cComptes]
    comment = Comptes - Oficines escriptura Direccio lectura
    path = /var/NovaCode/cComptes
    valid users = @gOficines @gDireccio
    write list = @gOficines
    read only = Yes
    browseable = Yes
    create mask = 0770
    directory mask = 0770

# cProjectes: gDesenvolupament escriptura, gDireccio lectura
# Lectura: uDirectora veu pero NO pot escriure
[cProjectes]
    comment = Projectes - Desenvolupament escriptura Direccio lectura
    path = /var/NovaCode/cProjectes
    valid users = @gDesenvolupament @gDireccio
    write list = @gDesenvolupament
    read only = Yes
    browseable = Yes
    create mask = 0770
    directory mask = 0770

# cProduccio: gDesenvolupament escriptura
[cProduccio]
    comment = Produccio - Desenvolupament
    path = /var/NovaCode/cProduccio
    valid users = @gDesenvolupament
    write list = @gDesenvolupament
    read only = No
    browseable = Yes
    create mask = 0770
    directory mask = 0770

# nomines: gOficines, fitxers privats del propietari (P4.7 Ex4)
[nomines]
    comment = Nomines - privat per propietari
    path = /var/NovaCode/nomines
    valid users = @gOficines
    write list = @gOficines
    read only = No
    browseable = Yes
    create mask = 0600
    directory mask = 0700
    force create mode = 0600
    force directory mode = 0700

# homes: directori personal per usuari (P4.7 Ex6)
[homes]
    comment = Directoris personals usuaris
    browseable = No
    read only = No
    valid users = %U %D%w%U
    path = /home/NovaCode/%S
    create mask = 0600
    directory mask = 0700
